<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function bv_vopros_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "environment_indicator" && $api == "default_environment_indicator_environments") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_vopros_question_status_reasons_alter().
 */
function bv_vopros_vopros_question_status_reasons_alter(&$reasons) {
  $reasons['asked for help'] = t('Asked for help');
}

/**
 * Implements hook_permission().
 */
function bv_vopros_permission() {
  return array(
    'bv can ask for help' =>  array(
      'title' => t('Can ask for help for vopros question'),
      'description' => t('The user is allowed to close questions with the ask for help status reason.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bv_vopros_form_vopros_question_close_question_form_alter(&$form, &$form_state) {
  if (user_access('bv can ask for help')) {
    $form['reason']['#options']['asked for help'] = t('Asked for help');
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for vopros_embed_question().
 *
 * Add in some extra checkboxes that lets us determine which editorial to give
 * the question.
 */
function bv_vopros_form_vopros_embed_question_alter(&$form, &$form_state) {
  // If question isn't set, vopros_embed is displaying an error message, so
  // don't add the checkboxes.
  if (isset($form['question'])) {
    if (module_exists('vopros_editorial')) {
      $form['bv_article'] = array(
        '#type' => 'checkbox',
        '#title' => t('The question concerns an article.'),
        '#states' => array(
          'visible' => array(
            'input[name=user_answer_preference]' => array('value' => 'mail'),
          ),
        ),
        '#weight' => -9,
      );

      $form['bv_education'] = array(
        '#type' => 'checkbox',
        '#title' => t('The answer is to be used in higher education.'),
        '#states' => array(
          'visible' => array(
            'input[name=user_answer_preference]' => array('value' => 'mail'),
          ),
        ),
        '#weight' => -8,
      );

      // Prepend our submit handler so we can mess with $form_state['values']
      // before the form submit handler gets at it.
      array_unshift($form['#submit'], 'bv_vopros_vopros_embed_question_submit');
    }
  }
}

/**
 * Form submission handler.
 */
function bv_vopros_vopros_embed_question_submit(&$form, &$form_state) {
  $question = $form_state['values']['question'];
  $question_wrapper = entity_metadata_wrapper('vopros_question', $question);

  // Default to "Folkebibliotek".
  $question_wrapper->vopros_editorial->set(2);
  if ($form_state['values']['user_answer_preference'] === 'mail' &&
      ($form_state['values']['bv_article'] ||
       $form_state['values']['bv_education'])) {
    // Override to "Forskningsbibliotek".
    $question_wrapper->vopros_editorial->set(1);
  }
}
