<?php

/*
 * Implements hook_menu().
 */
function chatty_menu() {
  $items = array();

  // Get routes.
  $items['chatty/api/v1/questions'] = array(
    'page callback' => 'get_questions_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.get.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/question'] = array(
    'page callback' => 'get_question_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.get.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/messages'] = array(
    'page callback' => 'get_messages_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.get.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/settings'] = array(
    'page callback' => 'get_settings_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.get.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/consultant-name'] = array(
    'page callback' => 'get_consultant_name_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.get.inc',
    'type' => MENU_CALLBACK,
  );

  // Post routes.
  $items['chatty/api/v1/create-question'] = array(
    'page callback' => 'create_question_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.post.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/create-message'] = array(
    'page callback' => 'create_message_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.post.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/assign-question'] = array(
    'page callback' => 'assign_question_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.post.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/close-question'] = array(
    'page callback' => 'close_question_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.post.inc',
    'type' => MENU_CALLBACK,
  );
  $items['chatty/api/v1/reopen-question'] = array(
    'page callback' => 'reopen_question_callback',
    'access callback' => TRUE,
    'delivery callback' => 'drupal_json_output',
    'file' => 'includes/api.post.inc',
    'type' => MENU_CALLBACK,
  );

  // Administrative pages.
  $items['admin/config/chatty/settings'] = array(
    'title' => 'Chat settings',
    'description' => 'Configure chatty settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chatty_setting_form'),
    'access arguments' => array('administer chatty'),
    'file' => 'includes/admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function chatty_permission() {
  return array(
    'administer chatty' => array(
      'title' => t('Administer chat settings'),
      'description' => '',
    ),
  );
}

/**
 * Access callback.
 *
 * Grants access if the user have administer chatty permission.
 */
function chatty_access() {
  if (user_access('administer chatty')) {
    return TRUE;
  }

  return FALSE;
}
