const NEW_MESSAGE = 'NEW_MESSAGE';
const NEW_QUESTION = 'NEW_QUESTION';
const QUESTION_ASSIGNED_TO_CONSULTANT = 'QUESTION_ASSIGNED_TO_CONSULTANT';
const QUESTION_ASSIGNED = 'QUESTION_ASSIGNED';
const ASSIGNED_QUESTION_CLOSED = 'ASSIGNED_QUESTION_CLOSED';
const QUESTION_CLOSED = 'QUESTION_CLOSED';
const QUESTION_REOPENED = 'QUESTION_REOPENED';

module.exports = {
  NEW_MESSAGE,
  NEW_QUESTION,
  ASSIGNED_QUESTION_CLOSED,
  QUESTION_ASSIGNED_TO_CONSULTANT,
  QUESTION_ASSIGNED,
  QUESTION_CLOSED,
  QUESTION_REOPENED,
};
